rules/impl.bzl, src/cli/AndroidLintActionArgs.kt, src/cli/AndroidLintRunner.kt, tests/src/cli/AndroidLintActionArgsTest.kt, toolchains/toolchain.bzl
Pulling `enable_check_dependencies` support up into the toolchain.
=> Support enabling enable_check_dependencies at the toolchain level

src/cli/AndroidLintCliInvoker.kt, src/cli/AndroidLintRunner.kt
Extracts the Android Lint invocation logic out into a invoker that uses reflection, allowing support for dynamically setting lint.
=> Add AndroidLintCliInvoker to wrap Android Lint

rules/impl.bzl, toolchains/toolchain.bzl
Pulls `android_lint_skip_bytecode_verifier` up to the toolchain so that it can be toggled.
=> Pull android_lint_skip_bytecode_verifier up to the toolchain

rules/impl.bzl, src/cli/AndroidLintActionArgs.kt, src/cli/AndroidLintCliInvoker.kt, src/cli/AndroidLintRunner.kt, src/cli/BUILD, tests/src/cli/AndroidLintActionArgsTest.kt, third_party/BUILD.bazel, toolchains/toolchain.bzl
Decouples lint from the Android Lint CLI tool allowing the version to be dynamically set at the toolchain level.
The new toolchain field current expects a single deploy jar containing the complete classpath.
=> Decouple the rule set from the lint cli tool

rules/impl.bzl
I disabled this while re-organizing everything. Enabling it again by default.
=> Flip supports-multiplex-workers back on

README.md
Removing the experimental status from the README since a few companies are using these rules in large production environments already.
=> Remove experimental status from README.md

src/cli/AndroidLintRunner.kt
Lint has been known to scape the sandbox. Passing this flag further isolates by having it keep any caches that it creates inside the worker tmp. directory that gets wiped after the action finishes.
=> Pass --cache-dir to further sandbox lint

src/cli/AndroidLintRunner.kt
Before running the AndroidLintCLI, there may be times in new invocations where you are not guaranteed to have the android-cache folder.
This fix will guarantee the folder exists before writing to it.
=> Fixing Bug With Android Folder in Runner

rules/impl.bzl
We are running into a bug where if other Android libraries are being added, we will fail compilation because other AndroidManifest.xml are being added to the compilation.
Since this classpath check is only for aar and jar files, we want to filter out files that don't conform.
=> Bug with Android Manifest being added from dependent libraries

.github/workflows/ci.yaml
Pulling in the latest stable releases for both 6.x and 7.x.
=> [CI] Bump Bazel versions to 6.5.0 and 7.1.1

.github/workflows/ci.yaml
Syncing the CI related changes with the upstream bazel-control template
https://github.com/bazel-contrib/rules-template/pull/109
=> [CI] Don't cancel builds on main branch

src/cli/AndroidLintRunner.kt
Lint implementation can change behavior based on passed `client-id`s. Among various recognized ids like `test`, `gradle`, `studio`, cli is the most appropriate one and this PR passes it to lint cli.
Observed internally that certain [detectors](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:lint/libs/lint-api/src/main/java/com/android/tools/lint/detector/api/LintFix.kt;l=1786;drc=042516205eef87810ffe9f6d51ba40b1edbb15b0) require client id to be set
=> Pass `client-id` to lint cli

rules/impl.bzl, src/cli/AndroidLintActionArgs.kt, src/cli/AndroidLintRunner.kt, toolchains/toolchain.bzl
Directly inject android_home into lint and reconstructs the absolute path without resorting to using the ANDROID_HOME environment variable outside of Bazel.
This is opposed to [Grab's approach.](https://github.com/grab/grab-bazel-common/blob/02735d57ab96392d9b590398218a6be3e1f[…]3813f/tools/lint/src/main/java/com/grab/lint/LintBaseCommand.kt](https://github.com/grab/grab-bazel-common/blob/02735d57ab96392d9b590398218a6be3e1f3813f/tools/lint/src/main/java/com/grab/lint/LintBaseCommand.kt#L213C28-L213C40) that constructs the field from environment variable.
How to Use:
android_lint_test(
**android_home = "@androidsdk//:sdk",**
)
This way, we keep the sdk in parity with whatever we have specified in WORKSPACE.
=> Adding Android Home support

.gitignore
Adding `MODULE.bazel.lock` to the gitignore so that it doesn't get accidentally checked in.
=> Add MODULE.bazel.lock to .gitignore

.bazelrc
This is enabled by default in 7.1.1
https://github.com/bazelbuild/bazel/blob/release-7.1.1/src/main/java/com/google/devtools/build/lib/packages/semantics/BuildLanguageOptions.java#L197-L206
=> [Bzlmod] Remove enable_bzlmod now that it's enabled by default

.github/workflows/ci.yaml
This is no longer supported moving forward.
=> Drop Bazel 6.x from ci.yaml

.bazelrc, MODULE.bazel, docs/rules.md, rules/BUILD.bazel, rules/impl.bzl
Running `bazel build :lint` with bazel version 8 and was able to run successfully after adding `rules_android` bazel dep.
=> Load rules_android and providers

.github/workflows/ci.yaml
Bumping the Bazel version again after this landed https://github.com/Bencodes/rules_android_lint/pull/71
=> Update ci.yaml to use Bazel 8.0.1

.bazelrc, MODULE.bazel
Updating the rules_android version that these rules depend on to 0.6.1 for the visibility fixes that we needed.
=> Update rules_android to 0.6.1

rules/attrs.bzl, rules/impl.bzl, src/cli/AndroidLintActionArgs.kt, src/cli/AndroidLintRunner.kt
Passing the JDK to AndroidLint so that it has these types available.
=> Pass the JDK to Lint
